project_name: platform-cli

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: platform
    binary: platform
    main: .
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ava-labs/platform-cli/cmd.version={{.Version}}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

archives:
  - id: platform
    builds:
      - platform
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: ava-labs
    name: platform-cli
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
